#!/bin/bash
PPATH=$(realpath ..)
. ../../testdata_tools/gen.sh

setup_dirs

use_solution ../regskylt_js.cpp

compile random_generator.py # Arguments: n k case seed

samplegroup
sample sample

group known 13
tc known-1 random_generator 100000 1 known
tc known-2 random_generator 100000 2 known
tc known-3 random_generator 100000 10 known
tc known-4 random_generator 100000 100 known
tc known-5 random_generator 100000 1000 known
tc known-6 random_generator 100000 10000 known
tc known-7 random_generator 100000 100000 known

group zeroes 31
tc zeroes-1 random_generator 100000 1 zeroes
tc zeroes-2 random_generator 100000 1 zeroes

group small 20
tc known-1 random_generator 1000 1 ''
tc known-2 random_generator 1000 2 ''
tc known-3 random_generator 1000 10 ''
tc known-4 random_generator 1000 100 ''
tc known-5 random_generator 1000 1000 ''

group large 36
include_group known
include_group zeroes
include_group small
tc known-1 random_generator 100000 1 ''
tc known-2 random_generator 100000 2 ''
tc known-3 random_generator 100000 10 ''
tc known-4 random_generator 100000 100 ''
tc known-5 random_generator 100000 1000 ''
tc known-6 random_generator 100000 10000 ''
tc known-7 random_generator 100000 100000 ''

generate_grader
generate_cms
cleanup_programs
