#!/bin/bash
PPATH=$(realpath ..)
. ../../testdata_tools/gen.sh

setup_dirs

use_solution ../sol.cpp

compile randomGenerator.cpp # Arguments: n k seed
compile genPath.py # Arguments: n each seed
compile genOverflow.py
compile genOverflow2.py

samplegroup
sample 1

# P = 2, N <= 1000
group two 8
tc overflow-1 genOverflow
tc overflow-2 genOverflow2

# N <= 1000, C_i > 0
group medium_pos 10
tc overflow-1
tc overflow-2

# N <= 1000, the tree is a line
group line 16
tc overflow-1
tc overflow-2
tc path-1 genPath 1000 1
tc path-2 genPath 1000 2
tc path-3 genPath 1000 -5

# N <= 1000
group medium 18
include_group two
include_group medium_pos
include_group line

# N <= 100,000, C_i > 0
group large_pos 18
include_group medium_pos

# N <= 100,000
group large 30
include_group large_pos
include_group medium

generate_grader
generate_cms
cleanup_programs
